
#  zipkin:
#    enabled: true
#    base-url: ${ZIPKIN_SERVER:http://localhost:9411/}


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
      register-with-eureka: true
      fetch-registry: true

message: Welcome to the Store
