


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
      register-with-eureka: true
      fetch-registry: true

message: Welcome to the Manoj Trichy k k nager Store no.3
